export const apartmentConstants = {
  CREATE_APARTMENT_SUCCESS: "CREATE_APARTMENT_SUCCESS",
  UPDATE_CURRENT_APARTMENT: "UPDATE_CURRENT_APARTMENT",
  SET_CURRENT_APARTMENT: "SET_CURRENT_APARTMENT"
};
